#!/usr/bin/env bash
# Write a Bash script that displays: To infinity and beyond indefinitely
# with a sleep 2 in between each iteration and I am invicible!!! when recieving a SIGTERM signal

msg()
{
echo "I am invicible!!!"
}

trap "msg" SIGTERM

while true
do
echo "To infinity and beyond"
sleep 2
done
