#!/usr/bin/env bash
# Script gives info on file (exist? wmpty? file and not directory?)

file="school"
if [ -e "$file" ]; then
echo "$file file exists"
if [ -s "$file file ]; then
echo "$file file is not empty"
else
echo "$file file is empty"
fi
if [ -f "$file" ]; then
echo "$file is regular file"
fi
else
echo "$file file does not exist"
fi
